baseURL: "https://www.hossain.cc/"
title: Kazi Hossain
paginate: 5
theme: LightPaper

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true



params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kazi Hossain
  description: "Kazi Hossain personal website"
  keywords: [Kazi Hossain, kazi hossain personal website, Kazi Hossain Blog, Kazi Hossain NYU, Kazi Hossain Projects, personal website]
  author: ["Kazi Hossain"]
  # author: ["Me", "You"] # multiple authors
  images: ["https://raw.githubusercontent.com/kazisean/hossain.cc/main/static/meta/twitter_banner.jpeg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16:  "https://raw.githubusercontent.com/kazisean/hossain.cc/main/static/fav/favicon-16x16.png"
    favicon32x32:  "https://raw.githubusercontent.com/kazisean/hossain.cc/main/static/fav/favicon-32x32.png"
    apple_touch_icon:  "https://raw.githubusercontent.com/kazisean/hossain.cc/main/static/fav/apple-touch-icon.png"

  label:
    text: "Kazi"
    icon:  
    iconHeight: 40


  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Kazi Hossain
    subtitle: "Machine learning, Mathematics & Aerospace 🚀"
    imageUrl: "https://i.pinimg.com/564x/73/8f/f2/738ff21d48adbdf664fcbc26f4cde532.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Profile Picture of Kazi Hossain from his Personal Website and Blog 
    buttons:
      - name: All Posts
        url: posts
      - name: Topics
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Kazi Hossain."
    Content: Machine Learning, Aerospace and Foss enthusiast.

  socialIcons:
    - name: cv
      url: "#"
    - name: email
      url: mailto:kazi.h[at]nyu.edu
    - name: github
      url: "https://github.com/kazisean"
    - name: rss
      url: "https://www.hossain.cc/sitemap.xml"

  analytics:
    google:
      SiteVerificationTag: "h9unPlnjf006WcSUHEy_Ra2GawD6Ws8vyZs3KnDVeXM"
    bing:
      SiteVerificationTag: "FE80A8C0F4A25DC1D8CD653BED312738"
   
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/kazisean/hossain.cc/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: archive
      name: All Post
      url: /posts/
      weight: 20
    # - identifier: topics
    #   name: Topics
    #   url: /tags/
    #   weight: 30
    - identifier: notes
      name: Notes
      url: /notes/
      weight: 40
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 50
    - identifier: about
      name: About
      url: /
      weight: 80
    - identifier: misc
      name: Misc
      url: /misc/
      weight: 60
    - identifier: links
      name: Links
      url: /links/
      weight: 70
    # - identifier: resume
    #   name: Resume
    #   url: 
    #   weight: 80

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary